### ISSUE TITLE
Failure to compile on Ubuntu 17.04 LTS

### ISSUE THREAD

**Issue by TechdudeGames** [waneck/linux-ios-toolchain#20]
I attempted to build the tool-chain on Ubuntu 17.04 LTS 64bit, but in doing so it generated an error:
code-sign-blobs/memutils.h:94:42: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline const T *increment(const void *p, ptrdiff_t offset)
                                         ^~~~~~~~~
                                         std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:98:30: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline T *increment(void *p, ptrdiff_t offset)
                             ^~~~~~~~~
                             std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:101:45: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline const void *increment(const void *p, ptrdiff_t offset)
                                            ^~~~~~~~~
                                            std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:104:33: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline void *increment(void *p, ptrdiff_t offset)
                                ^~~~~~~~~
                                std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:108:42: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline const T *increment(const void *p, ptrdiff_t offset, size_t alignment)
                                         ^~~~~~~~~
                                         std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:112:30: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline T *increment(void *p, ptrdiff_t offset, size_t alignment)
                             ^~~~~~~~~
                             std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:115:45: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline const void *increment(const void *p, ptrdiff_t offset, size_t alignment)
                                            ^~~~~~~~~
                                            std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:118:33: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline void *increment(void *p, ptrdiff_t offset, size_t alignment)
                                ^~~~~~~~~
                                std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:121:8: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline ptrdiff_t difference(const void *p1, const void *p2)
       ^~~~~~~~~
       std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^

**Comment by tpoechtrager** [comment]
Should be fixed in more recent versions of [cctools-port](https://github.com/tpoechtrager/cctools-port). The version this tool chain is using is almost 3 years old.

**Comment by TechdudeGames** [comment]
Ok. That makes sense. Thanks!

**Comment by waneck** [comment]
@tpoechtrager is right. I should actually deprecate this in favor of his well-maintained project!
